### ISSUE TITLE
No validity check between two guarantees/constraints with the same id.

### ISSUE THREAD

**Issue by pafmon** [isa-group/ideas-iagree-module#1]
Error case:
<pre>
GuaranteeTerms
    A: Provider guarantees x < 1;
    A: Provider guarantees x > 1;
-------------------------------------------------
Check Validity --> The document is consistent
</pre>

This case should show a parser error to warn about two guarantees with the same id

**Comment by pafmon** [comment]
Same error should happend in the case of two constraints

**Comment by juanlu91** [comment]
This issue was moved to isa-group/aml#60
